[build]
  publish = "."

[[headers]]
  for = "/admin/config.yml"
  [headers.values]
    Content-Type = "text/yaml"

[[redirects]]
  from = "/.netlify/identity/*"
  to = "/.netlify/identity/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
  force = true
