[build]
  publish = "public"  # Change ce dossier selon ton projet (ex: "dist" si tu utilises un build)

[[redirects]]
  from = "/.netlify/identity/*"
  to = "/admin"
  status = 200
  force = true

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
  force = true
